// src/mockdata/problems.js

export default [
  {
    id: 1,
    problemNumber: 1000,
    title: 'A+B',
    tier: 'Bronze V',
    url: 'https://www.acmicpc.net/problem/1000',
    isSolved: true,
    algorithms: ['수학', '구현', '사칙연산'],
  },
  {
    id: 2,
    problemNumber: 1001,
    title: 'A-B',
    tier: 'Bronze V',
    url: 'https://www.acmicpc.net/problem/1001',
    isSolved: true,
    algorithms: ['수학', '구현', '사칙연산'],
  },
  {
    id: 3,
    problemNumber: 1008,
    title: 'A/B',
    tier: 'Bronze V',
    url: 'https://www.acmicpc.net/problem/1008',
    isSolved: false,
    algorithms: ['수학', '구현', '사칙연산'],
  },
  {
    id: 4,
    problemNumber: 1463,
    title: '1로 만들기',
    tier: 'Silver III',
    url: 'https://www.acmicpc.net/problem/1463',
    isSolved: true,
    algorithms: ['다이나믹 프로그래밍'],
  },
  {
    id: 5,
    problemNumber: 2606,
    title: '바이러스',
    tier: 'Silver III',
    url: 'https://www.acmicpc.net/problem/2606',
    isSolved: false,
    algorithms: ['그래프 이론', '그래프 탐색', '너비 우선 탐색', '깊이 우선 탐색'],
  },
  {
    id: 6,
    problemNumber: 11726,
    title: '2×n 타일링',
    tier: 'Silver III',
    url: 'https://www.acmicpc.net/problem/11726',
    isSolved: true,
    algorithms: ['다이나믹 프로그래밍'],
  },
  {
    id: 7,
    problemNumber: 1904,
    title: '01타일',
    tier: 'Silver III',
    url: 'https://www.acmicpc.net/problem/1904',
    isSolved: false,
    algorithms: ['다이나믹 프로그래밍'],
  },
  {
    id: 8,
    problemNumber: 9461,
    title: '파도반 수열',
    tier: 'Silver III',
    url: 'https://www.acmicpc.net/problem/9461',
    isSolved: true,
    algorithms: ['다이나믹 프로그래밍'],
  },
  {
    id: 9,
    problemNumber: 1932,
    title: '정수 삼각형',
    tier: 'Silver I',
    url: 'https://www.acmicpc.net/problem/1932',
    isSolved: false,
    algorithms: ['다이나믹 프로그래밍'],
  },
  {
    id: 10,
    problemNumber: 2579,
    title: '계단 오르기',
    tier: 'Silver III',
    url: 'https://www.acmicpc.net/problem/2579',
    isSolved: true,
    algorithms: ['다이나믹 프로그래밍'],
  },
  {
    id: 11,
    problemNumber: 1149,
    title: 'RGB거리',
    tier: 'Silver I',
    url: 'https://www.acmicpc.net/problem/1149',
    isSolved: false,
    algorithms: ['다이나믹 프로그래밍'],
  },
  {
    id: 12,
    problemNumber: 1012,
    title: '유기농 배추',
    tier: 'Silver II',
    url: 'https://www.acmicpc.net/problem/1012',
    isSolved: true,
    algorithms: ['그래프 이론', '그래프 탐색', '너비 우선 탐색', '깊이 우선 탐색'],
  },
  {
    id: 13,
    problemNumber: 2667,
    title: '단지번호붙이기',
    tier: 'Silver I',
    url: 'https://www.acmicpc.net/problem/2667',
    isSolved: false,
    algorithms: ['그래프 이론', '그래프 탐색', '너비 우선 탐색', '깊이 우선 탐색'],
  },
  {
    id: 14,
    problemNumber: 7576,
    title: '토마토',
    tier: 'Gold V',
    url: 'https://www.acmicpc.net/problem/7576',
    isSolved: false,
    algorithms: ['그래프 이론', '그래프 탐색', '너비 우선 탐색'],
  },
  {
    id: 15,
    problemNumber: 1697,
    title: '숨바꼭질',
    tier: 'Silver I',
    url: 'https://www.acmicpc.net/problem/1697',
    isSolved: true,
    algorithms: ['그래프 이론', '그래프 탐색', '너비 우선 탐색'],
  },
  {
    id: 16,
    problemNumber: 2178,
    title: '미로 탐색',
    tier: 'Silver I',
    url: 'https://www.acmicpc.net/problem/2178',
    isSolved: false,
    algorithms: ['그래프 이론', '그래프 탐색', '너비 우선 탐색'],
  },
  {
    id: 17,
    problemNumber: 7569,
    title: '토마토',
    tier: 'Gold V',
    url: 'https://www.acmicpc.net/problem/7569',
    isSolved: false,
    algorithms: ['그래프 이론', '그래프 탐색', '너비 우선 탐색'],
  },
  {
    id: 18,
    problemNumber: 1991,
    title: '트리 순회',
    tier: 'Silver I',
    url: 'https://www.acmicpc.net/problem/1991',
    isSolved: true,
    algorithms: ['트리', '재귀'],
  },
  {
    id: 19,
    problemNumber: 11725,
    title: '트리의 부모 찾기',
    tier: 'Silver II',
    url: 'https://www.acmicpc.net/problem/11725',
    isSolved: false,
    algorithms: ['그래프 이론', '그래프 탐색', '트리', '너비 우선 탐색', '깊이 우선 탐색'],
  },
  {
    id: 20,
    problemNumber: 1167,
    title: '트리의 지름',
    tier: 'Gold II',
    url: 'https://www.acmicpc.net/problem/1167',
    isSolved: false,
    algorithms: ['그래프 이론', '그래프 탐색', '트리', '깊이 우선 탐색'],
  },
]
