// src/mockdata/teams.js

export default [
  {
    id: 1,
    name: 'S급 해결사',
    description: '알고리즘 문제를 빠르게 해결하는 팀입니다!',
    memberCount: 12,
    maxMembers: 15,
    tier: 'Ruby V',
    totalRating: 2745,
    leader: 'shiftpsh',
    createdAt: '2024-01-15',
    tags: ['경쟁 프로그래밍', '코딩테스트', '고급'],
    isJoined: false,
    members: [
      { username: 'shiftpsh', tier: 'Ruby V', rating: 2745, role: 'leader' },
      { username: '지민_빈', tier: 'Ruby V', rating: 2740, role: 'member' },
      { username: '알고마스터', tier: 'Diamond I', rating: 2600, role: 'member' },
      { username: '코딩왕', tier: 'Diamond II', rating: 2550, role: 'member' },
    ],
  },
  {
    id: 2,
    name: '알고왕',
    description: '함께 성장하는 알고리즘 스터디 팀',
    memberCount: 8,
    maxMembers: 10,
    tier: 'Ruby V',
    totalRating: 2740,
    leader: '알고마스터',
    createdAt: '2024-02-01',
    tags: ['스터디', '꾸준함', '고급'],
    isJoined: true,
    members: [
      { username: '알고마스터', tier: 'Ruby V', rating: 2740, role: 'leader' },
      { username: '코딩러', tier: 'Diamond I', rating: 2650, role: 'member' },
      { username: '문제해결사', tier: 'Diamond II', rating: 2580, role: 'member' },
    ],
  },
  {
    id: 3,
    name: '자료구조 마스터즈',
    description: '자료구조와 알고리즘의 깊은 이해를 추구합니다',
    memberCount: 6,
    maxMembers: 8,
    tier: 'Ruby IV',
    totalRating: 2720,
    leader: '자료구조왕',
    createdAt: '2024-01-28',
    tags: ['자료구조', '알고리즘', '심화'],
    isJoined: false,
    members: [
      { username: '자료구조왕', tier: 'Ruby IV', rating: 2720, role: 'leader' },
      { username: '트리마스터', tier: 'Diamond I', rating: 2620, role: 'member' },
    ],
  },
  {
    id: 4,
    name: '코테 준비생',
    description: '코딩테스트 합격을 목표로 하는 팀',
    memberCount: 15,
    maxMembers: 20,
    tier: 'Ruby IV',
    totalRating: 2710,
    leader: '취준생123',
    createdAt: '2024-03-05',
    tags: ['코딩테스트', '취업준비', '중급'],
    isJoined: false,
    members: [
      { username: '취준생123', tier: 'Ruby IV', rating: 2710, role: 'leader' },
      { username: '화이팅맨', tier: 'Diamond III', rating: 2500, role: 'member' },
      { username: '노력왕', tier: 'Platinum I', rating: 2450, role: 'member' },
    ],
  },
  {
    id: 5,
    name: '백준 러버즈',
    description: '백준 문제를 사랑하는 사람들의 모임',
    memberCount: 9,
    maxMembers: 12,
    tier: 'Ruby III',
    totalRating: 2690,
    leader: '백준러버',
    createdAt: '2024-02-14',
    tags: ['백준', '문제풀이', '일반'],
    isJoined: false,
    members: [
      { username: '백준러버', tier: 'Ruby III', rating: 2690, role: 'leader' },
      { username: '문제풀이맨', tier: 'Diamond I', rating: 2600, role: 'member' },
    ],
  },
  {
    id: 6,
    name: '초보자 환영',
    description: '알고리즘을 처음 시작하는 분들을 위한 팀',
    memberCount: 18,
    maxMembers: 25,
    tier: 'Silver I',
    totalRating: 1850,
    leader: '선배님',
    createdAt: '2024-03-10',
    tags: ['초보자', '기초', '친화적'],
    isJoined: false,
    members: [
      { username: '선배님', tier: 'Gold II', rating: 2100, role: 'leader' },
      { username: '새내기1', tier: 'Silver II', rating: 1600, role: 'member' },
      { username: '열정맨', tier: 'Silver III', rating: 1550, role: 'member' },
    ],
  },
  {
    id: 7,
    name: 'DP 마스터즈',
    description: '다이나믹 프로그래밍에 특화된 스터디 팀',
    memberCount: 5,
    maxMembers: 8,
    tier: 'Diamond I',
    totalRating: 2600,
    leader: 'DP왕',
    createdAt: '2024-02-20',
    tags: ['다이나믹 프로그래밍', '심화', '전문'],
    isJoined: false,
    members: [
      { username: 'DP왕', tier: 'Diamond I', rating: 2600, role: 'leader' },
      { username: '메모이제이션', tier: 'Platinum I', rating: 2400, role: 'member' },
    ],
  },
  {
    id: 8,
    name: '그래프 탐험가',
    description: '그래프 알고리즘을 정복하는 팀',
    memberCount: 7,
    maxMembers: 10,
    tier: 'Platinum I',
    totalRating: 2400,
    leader: '그래프킹',
    createdAt: '2024-03-01',
    tags: ['그래프', 'DFS', 'BFS'],
    isJoined: false,
    members: [
      { username: '그래프킹', tier: 'Platinum I', rating: 2400, role: 'leader' },
      { username: 'DFS러버', tier: 'Gold I', rating: 2200, role: 'member' },
    ],
  },
]
