spring:
    datasource:
        url: jdbc:mysql://localhost:3306/ssafyforce
        username: ssafy
        password: ssafy
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        database-platform: org.hibernate.dialect.MySQL8Dialect
        properties:
            hibernate:
                default_batch_fetch_size: 1000

    logging:
        level:
            org.hibernate.SQL: debug
            org.hibernate.type: trace
            com.baekjoon.team: debug
            force.ssafy.global.security: DEBUG
            org.springframework.security: DEBUG


jwt:
    secret: backjoonTeamCompetitionApplicationSecretKey2023!@#$
    token:
        access-expiration-time: 3600000  # 1시간
        refresh-expiration-time: 1209600000  # 14일
